global:

  ecrRegistry: "039968205787.dkr.ecr.us-east-1.amazonaws.com" # <--- Thay bằng output của Terraform
  imageTag: "v1.0.55"

imagePullSecrets:
  - name: regcred

api:
  image:
    name: "tubemind/api-gateway"
    pullPolicy: Always
  env:
    MINIO_ENDPOINT: "s3.amazonaws.com"

transcriber:
  image:
    name: "tubemind/transcriber"
    pullPolicy: Always
  # Worker này ko dùng env từ values nhiều vì worker.yaml đã fix cứng/lấy từ global

summarizer:
  image:
    name: "tubemind/summarizer"
    pullPolicy: Always

notifier:
  image:
    name: "tubemind/notifier"
    pullPolicy: Always
  env:
    SMTP_HOST: "email-smtp.us-east-1.amazonaws.com"
    SMTP_PORT: 587
    EMAIL_FROM: "huyhoang.190904@gmail.com"

external:
  db:
    host: "tubemind-postgres-db.co7gewgmyvve.us-east-1.rds.amazonaws.com"
    port: 5432
    name: "tubemind_db"
    user: "tubemind_user"
  s3:
    bucketName: "tubemind-videos-20251229174127108100000001"
    region: "us-east-1"

redis:
  host: "tubemind-redis"
  port: 6379