global:

  ecrRegistry: "039968205787.dkr.ecr.us-east-1.amazonaws.com" # <--- Thay bằng output của Terraform
  imageTag: "v1.0.83"

imagePullSecrets:
  - name: regcred

api:
  image:
    name: "tubemind/api-gateway"
    pullPolicy: Always
  env:
    MINIO_ENDPOINT: "s3.amazonaws.com"

transcriber:
  image:
    name: "tubemind/transcriber"
    pullPolicy: Always
  # Worker này ko dùng env từ values nhiều vì worker.yaml đã fix cứng/lấy từ global

summarizer:
  image:
    name: "tubemind/summarizer"
    pullPolicy: Always

notifier:
  image:
    name: "tubemind/notifier"
    pullPolicy: Always
  env:
    EMAIL_FROM: "huyhoang.190904@gmail.com"

external:
  db:
    host: "tubemind-postgres-db.co7gewgmyvve.us-east-1.rds.amazonaws.com"
    port: 5432
    name: "tubemind_db"
    user: "tubemind_user"
  s3:
    bucketName: "tubemind-videos-20251229174127108100000001"
    region: "us-east-1"

redis:
  host: "tubemind-redis"
  port: 6379

# Cấu hình Monitoring tập trung
prometheus:
  enabled: true
  kube-prometheus-stack:
    prometheus:
      prometheusSpec:
        retention: 1d
        storageSpec: {} 
        resources:
          limits:
            memory: "800Mi"
          requests:
            memory: "400Mi"
    grafana:
      adminPassword: "admin"
      service:
        type: NodePort
        nodePort: 32000
      # Sửa lỗi: Đảm bảo sidecar tự động quét DataSources
      sidecar:
        datasources:
          enabled: true
          defaultDatasourceEnabled: true # Ưu tiên Prometheus làm mặc định

loki:
  enabled: true
  loki-stack:
    loki:
      isDefault: false # Quan trọng: Tắt mặc định của Loki để tránh lỗi 500 trong log
      persistence:
        enabled: false 
      resources:
        limits:
          memory: "400Mi"
    promtail:
      resources:
        limits:
          memory: "200Mi"
      # Cấu hình Promtail để nó biết gửi log về Service nào
      config:
        lokiAddress: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push