version: '3.8'

services:
  # 1. Database: PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: tubemind-postgres
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: tubemind_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tubemind-net

  # 2. Message Queue: Redis
  redis:
    image: redis:7-alpine
    container_name: tubemind-redis
    ports:
      - "6379:6379"
    networks:
      - tubemind-net

  # 3. MinIO (Giả lập AWS S3)
  minio:
    image: minio/minio
    container_name: tubemind-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API Port (Code gọi vào đây)
      - "9001:9001" # Console Port (Truy cập web UI)
    volumes:
      - minio_data:/data
    networks:
      - tubemind-net

  # Tool tạo Bucket trong MinIO khi khởi động
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio_admin minio_password;
      /usr/bin/mc mb myminio/tubemind-videos;
      /usr/bin/mc anonymous set public myminio/tubemind-videos;
      exit 0;
      "
    networks:
      - tubemind-net

  # 4. Mock Email: Mailhog (Thay thế aws sns để thử nghiệm gửi email)
  mailhog:
    image: mailhog/mailhog
    container_name: tubemind-mailhog
    ports:
      - "1025:1025" # SMTP port (Service Notifier gửi mail vào đây)
      - "8025:8025" # Web UI (Vào xem mail đã gửi chưa)
    networks:
      - tubemind-net

networks:
  tubemind-net:
    driver: bridge

volumes:
  postgres_data:
  minio_data: