apiVersion: v1
kind: Secret
metadata:
  name: tubemind-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.external.db.password | quote }}
  # Nếu có AWS Key thì bỏ vào đây
  AWS_ACCESS_KEY_ID: {{ .Values.external.s3.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.external.s3.secretKey | quote }}