QUEUE_TRANSCRIBE = "queue:transcribe"
QUEUE_SUMMARIZE = "queue:summarize"
QUEUE_NOTIFY = "queue:notify"

STATUS_PENDING = "pending"
STATUS_TRANSCRIBING = "transcribing"
STATUS_TRANSCRIPTION_DONE = "transcription_done"
STATUS_PROCESSING = "processing"
STATUS_SUMMARIZING = "summarizing"
STATUS_COMPLETED = "completed" 
STATUS_FAILED = "failed"
QUEUE_NOTIFIER = "queue:notifier"

NOTIF_TRANSCRIPTION_DONE = "transcription_done"
NOTIF_SUMMARY_DONE = "summary_done"